[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.16"
regex = "1.11.1"

[[bench]]
name = "one"
harness = false

[[bench]]
name = "two"
harness = false

[[bench]]
name = "three"
harness = false

[[bench]]
name = "four"
harness = false

[[bench]]
name = "five"
harness = false

[[bench]]
name = "six"
harness = false

[[bench]]
name = "seven"
harness = false

[[bench]]
name = "eight"
harness = false

[[bench]]
name = "nine"
harness = false

[[bench]]
name = "ten"
harness = false
